// Database :)
function ListLunch() {
  return {
    risotto: {
      name: "Risotto",
      nb_person: 4,
      recipe: {
        "Cube de bouillon": 2,
        Oignon: 1,
        Echalote: 1,
        Beurre: "40g",
        "Riz Risotto": "320g",
        "Vin blanc": "100mL",
        Fenouil: 1,
        Champignons: "100g",
        "Crème fraîche": "50g",
        Parmesan: "100g",
      },
      formula: [
        "Préparer le bouillon et couper les légumes",
        "Cuire le fenouil dans un fait-tout avec fond d'huile et compléter en eau régulièrement",
        "Mettre le beurre dans la casserole et quand il est fini tu mets le riz",
        "Quand le riz est translucide, déglacer avec le vin blanc",
        "Mettre oignon, échalote et du bouillon doucement, quand il a disparu il faut en remettre",
        "À moitié du bouillon, mettre les champignons",
        "À la fin, mettre à feu très doux et ajouter crème, fenouil",
        "Quand il est sorti de la plaque, mettre le parmesan",
      ],
    },
    "poulet-moutarde": {
      name: "Poulet moutarde",
      nb_person: 4,
      recipe: {
        "Escalope de poulet": 4,
        "Crème fraîche": "5cL",
      },
      formula: [
        "Faire cuire à feu moyen les escalopes de poulet dans une poêle avec une noisette de beurre",
        "Dans un bol, mélangez la crème fraîche, la moutarde et le poivre",
        "Dans une petite casserole, faite chauffer queslques instants la sauce à feu doux",
        "Nappez les escalopes de poulet de sauce",
      ],
    },
    "chili-con-carne": {
      name: "Chili con carne",
      nb_person: 6,
      recipe: {
        Oignon: 1,
        "Viande hachée": "400g",
        "Haricots rouges": "400g",
        "Tomates pelées": "400g",
        Tomates: 2.5,
        Maïs: "400g",
      },
      formula: [
        "Faire revenir l'oignon avec l'huile d'olive dans une marmite",
        "Ajouter la viande hachée et le piment",
        "Quand la viande est à moitié cuite y ajouter les haricots rouges, les tomates et le maïs après les avoir égoutté",
        "Laisser mijoter",
        "Ajouter du piment en poudre selon le goût",
      ],
    },
    lasagnes: {
      name: "Lasagnes",
      nb_person: 6,
      recipe: {
        Oignon: 1,
        "Viande hachée": "400g",
        "Huile d'olives": "5cL",
        "Tomates pelées": "500g",
        Farine: "50g",
        Beurre: "50g",
        Lait: "50cL",
      },
      formula: [
        "Épluchez l’oignon et l’ail",
        "Mettez-les dans le robot muni du couteau hachoir Ultrablade. Mixez-les en vitesse 11 pendant 10 secondes",
        "Remplacez le couteau par le mélangeur et ajoutez l’huile. Lancez le programme mijoté P1 à 130°C pendant 5 minutes",
        "Ajoutez la viande, les tomates et l’origan. Salez et poivrez. Lancez le programme mijoté P2 à 90°C pendant 35 minutes",
        "Réservez la sauce et lavez le robot",
        "Préchauffez le four à 180°C (th. 6)",
        "Dans le robot muni du batteur, mettez la farine, le lait et la muscade. Salez et poivrez. Mixez en vitesse 7 pendant 1 minute",
        "Ajoutez le beurre et lancez le robot à 90°C en vitesse 4 pendant 8 minutes",
        "Huilez un plat à gratin et versez un peu de sauce tomate",
        "Couvrez de lasagnes, ajoutez de la sauce tomate, de la béchamel et du gruyère",
        "Renouvelez l’opération jusqu’à épuisement, en finissant par le gruyère",
        "Enfournez pendant 25 à 30 minutes",
      ],
    },
    crepes: {
      name: "Crêpes",
      nb_person: 2,
      recipe: {
        Farine: "250g",
        Oeuf: 4,
        Lait: "25cL",
        Bière: "25cL",
      },
      formula: ["Mélanger énergiquement tout sauf la bière", "Ajouter la bière et mélanger doucement"],
    },
  };
}
function ListDinner() {
  return {
    "pate-carbo": {
      name: "Pâtes à la Carbonara",
      nb_person: 2,
      recipe: {
        "Crème fraîche": "25cL",
        Oeuf: 2,
        Lardons: "125g",
        Oignon: 1,
        Pâtes: "250g",
      },
      formula: ["todo"],
    },
    pizza: {
      name: "Pizza",
      nb_person: 4,
      recipe: {
        "Pâte à pizza": 1,
        "Sauce tomate": 0.5,
        Champignons: "100g",
        Jambon: 2,
        Gruyère: "50g",
      },
      formula: ["Four à 200°C, pendant 15 minutes"],
    },
    "tarte-tomate": {
      name: "Tarte à la tomate",
      nb_person: 4,
      recipe: {
        "Pâte brisée": 1,
        Tomate: 5,
        Gruyère: "50g",
      },
      formula: ["todo"],
    },
    quiche: {
      name: "Quiche",
      nb_person: 4,
      recipe: {
        "Pâte brisée": 1,
        Oeuf: 3,
        Lardons: "200g",
        "Crème fraîche": "20cL",
        Lait: "20cL",
      },
      formula: ["todo"],
    },
    "tarte-poireaux": {
      name: "Tarte aux poireaux",
      nb_person: 4,
      recipe: {
        "Pâte brisée": 1,
        Poireaux: 3,
        Gruyère: "50g",
        "Crème fraîche": "5cL",
        Oeuf: 1,
      },
      formula: ["todo"],
    },
    "tarte-flambee": {
      name: "Tarte flambée",
      nb_person: 4,
      recipe: {
        Farine: "250g",
        Huile: "5cL",
        Oignon: 2,
        Lardons: "200g",
        "Fromage blanc": "100g",
        "Crème fraîche": "10cL",
        Gruyère: "50g",
      },
      formula: [
        "Préparez la pâte à l'aide d'un robot ou à la main. Mélangez la farine, ½ c. à café de sel, l'huile et progressivement 15 cl d'eau tiède",
        "Travaillez quelques minutes pour obtenir une pâte bien élastique, puis laissez reposer 1 heure à couvert",
        "Préchauffez votre four à 280°C. Émincez les oignons en fines lanières et faites-les fondre à feu doux pendant 5 min dans une noix de beurre, sans les colorer",
        "Faites rissoler rapidement les lardons",
        "Mélangez le fromage blanc et la crème, assaisonnez de sel, de poivre et de noix muscade",
      ],
    },
    "cake-jambon-olive": {
      name: "Cake Jambon Olive",
      nb_person: 4,
      recipe: {
        Farine: "150g",
        Jambon: "200g",
        "Olives vertes": "150g",
        Gruyère: "75g",
        Oeuf: 4,
        Lait: "10cL",
        "Levure chimique": 1,
      },
      formula: ["todo"],
    },
    "cake-menthe-feta": {
      name: "Cake Concombre Menthe Féta",
      nb_person: 4,
      recipe: {
        Farine: "150g",
        "Menthe fraîche": 1,
        Féta: "200gg",
        Oeuf: 4,
        "Huile d'olives": "10cL",
        "Crème fraîche": "15cL",
        "Levure chimique": 1,
        Concombre: 1,
      },
      formula: [
        "Retirer les grains du concombre, le découper en cubes et laisser dégorger dans une passoire avec un peu de sel pendant 30 minutes",
        "Mélanger les oeufs, la farine et la levure",
        "Y ajouter la crème, l'huile puis la menthe",
        "Préchauffer le four à 180°C et laisser reposer la pâte 30 minutes au frigo",
        "Couper la féta en cubes, puis étaler les concombre sur du papier absorbant",
        "Mélanger la pâte, les concombres et la féta",
        "Faire cuire 45 minutes au four dans un moule à cake",
      ],
    },
  };
}
